name: numpy_tutorial
channels:
  - conda-forge
dependencies:
  - python
  - ipython
  - jupyter
  - pillow
  - numpy
  - graphviz
  - matplotlib
  - notebook
  - pip
  - scikit-learn
  - scipy
  - ipywidgets
  - pip:
    - pydot-ng
